ABBREVIATIONS = { 
"ATL": "Atlanta Hawks",
"AND": "Anderson Packers",
"BKN": "Brooklyn Nets",
"BLB": "Baltimore Bullets",
"BOS": "Boston Celtics",
"BRK": "Brooklyn Nets",
"CHA": "Charlotte Hornets",
"CHI": "Chicago Bulls",
"CHH": "Chicago Hustle",
"CHO": "Chicago Bruins",
"CHP": "Chicago Packers/Zephyrs",
"CHZ": "Chicago Zephyrs",
"CHS": "Chicago Stags",
"CIN": "Cincinnati Royals",
"CLE": "Cleveland Cavaliers",
"DAL": "Dallas Mavericks",
"DEN": "Denver Nuggets",
"DNN": "Denver Nuggets",
"DET": "Detroit Pistons",
"FTW": "Fort Wayne Pistons",
"GSW": "Golden State Warriors",
"HOU": "Houston Rockets",
"IND": "Indiana Pacers",
"INO": "Indianapolis Olympians",
"LAC": "Los Angeles Clippers",
"LAL": "Los Angeles Lakers",
"MEM": "Memphis Grizzlies",
"MIA": "Miami Heat",
"MIL": "Milwaukee Bucks",
"MIN": "Minnesota Timberwolves",
"MLH": "Milwaukee Hawks",
"MNL": "Minnesota Lynx",
"NOP": "New Orleans Pelicans",
"NOH": "New Orleans Hurricanes",
"NOK": "New Orleans/Oklahoma City Hornets",
"NJN": "New Jersey Nets",
"NYK": "New York Knicks",
"OKC": "Oklahoma City Thunder",
"ORL": "Orlando Magic",
"PHI": "Philadelphia 76ers",
"PHW": "Philadelphia Warriors",
"PHX": "Phoenix Suns",
"PHO": "Phoenix Suns",
"POR": "Portland Trail Blazers",
"ROC": "Rochester Royals",
"SAC": "Sacramento Kings",
"SAS": "San Antonio Spurs",
"SEA": "Seattle Supersonics",
"SFW": "San Francisco Warriors",
"STB": "St. Louis Bombers",
"STL": "St. Louis Hawks",
"SHE": "Sheboygan Red Skins",
"SYR": "Syracuse Nationals",
"TOR": "Toronto Raptors",
"TOT": "Total",
"TRI": "Tri-Cities Blackhawks",
"UTA": "Utah Jazz",
"VAN": "Vancouver Grizzlies",
"WAS": "Washington Wizards",
"WAT": "Waterloo Hawks",
"WSC": "Washington Capitals" }